// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contexts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getContext = `-- name: GetContext :one
SELECT id, conversation_id, timestamp FROM contexts
WHERE id = $1
`

func (q *Queries) GetContext(ctx context.Context, id pgtype.UUID) (Context, error) {
	row := q.db.QueryRow(ctx, getContext, id)
	var i Context
	err := row.Scan(&i.ID, &i.ConversationID, &i.Timestamp)
	return i, err
}

const getContextByConversation = `-- name: GetContextByConversation :one
SELECT id, conversation_id, timestamp FROM contexts
WHERE conversation_id = $1
ORDER BY timestamp DESC
LIMIT 1
`

func (q *Queries) GetContextByConversation(ctx context.Context, conversationID pgtype.UUID) (Context, error) {
	row := q.db.QueryRow(ctx, getContextByConversation, conversationID)
	var i Context
	err := row.Scan(&i.ID, &i.ConversationID, &i.Timestamp)
	return i, err
}
