// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_queue.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimJob = `-- name: ClaimJob :one
UPDATE job_queue
SET state = 'processing',
    locked_until = now() + $2::interval,
    worker_id = $3
WHERE id = $1
RETURNING id, timestamp, worker_id, state, locked_until, payload
`

type ClaimJobParams struct {
	ID       pgtype.UUID
	Column2  pgtype.Interval
	WorkerID pgtype.UUID
}

func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (JobQueue, error) {
	row := q.db.QueryRow(ctx, claimJob, arg.ID, arg.Column2, arg.WorkerID)
	var i JobQueue
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.WorkerID,
		&i.State,
		&i.LockedUntil,
		&i.Payload,
	)
	return i, err
}

const dequeue = `-- name: Dequeue :one
UPDATE job_queue
SET state = 'processing',
    locked_until = now() + $1::interval
WHERE id = (
    SELECT id FROM job_queue
    WHERE state = 'pending'
    ORDER BY timestamp ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, timestamp, worker_id, state, locked_until, payload
`

func (q *Queries) Dequeue(ctx context.Context, dollar_1 pgtype.Interval) (JobQueue, error) {
	row := q.db.QueryRow(ctx, dequeue, dollar_1)
	var i JobQueue
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.WorkerID,
		&i.State,
		&i.LockedUntil,
		&i.Payload,
	)
	return i, err
}

const enqueue = `-- name: Enqueue :one
INSERT INTO job_queue (payload, worker_id)
VALUES ($1, $2)
RETURNING id, timestamp, worker_id, state, locked_until, payload
`

type EnqueueParams struct {
	Payload  []byte
	WorkerID pgtype.UUID
}

func (q *Queries) Enqueue(ctx context.Context, arg EnqueueParams) (JobQueue, error) {
	row := q.db.QueryRow(ctx, enqueue, arg.Payload, arg.WorkerID)
	var i JobQueue
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.WorkerID,
		&i.State,
		&i.LockedUntil,
		&i.Payload,
	)
	return i, err
}

const setDone = `-- name: SetDone :one
UPDATE job_queue
SET state = 'processed'
WHERE id = $1
RETURNING id, timestamp, worker_id, state, locked_until, payload
`

func (q *Queries) SetDone(ctx context.Context, id pgtype.UUID) (JobQueue, error) {
	row := q.db.QueryRow(ctx, setDone, id)
	var i JobQueue
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.WorkerID,
		&i.State,
		&i.LockedUntil,
		&i.Payload,
	)
	return i, err
}

const setErrored = `-- name: SetErrored :one
UPDATE job_queue
SET state = 'errored'
WHERE id = $1
RETURNING id, timestamp, worker_id, state, locked_until, payload
`

func (q *Queries) SetErrored(ctx context.Context, id pgtype.UUID) (JobQueue, error) {
	row := q.db.QueryRow(ctx, setErrored, id)
	var i JobQueue
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.WorkerID,
		&i.State,
		&i.LockedUntil,
		&i.Payload,
	)
	return i, err
}

const setWaiting = `-- name: SetWaiting :one
UPDATE job_queue
SET state = 'waiting'
WHERE id = $1
RETURNING id, timestamp, worker_id, state, locked_until, payload
`

func (q *Queries) SetWaiting(ctx context.Context, id pgtype.UUID) (JobQueue, error) {
	row := q.db.QueryRow(ctx, setWaiting, id)
	var i JobQueue
	err := row.Scan(
		&i.ID,
		&i.Timestamp,
		&i.WorkerID,
		&i.State,
		&i.LockedUntil,
		&i.Payload,
	)
	return i, err
}
