// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (context_id, role, content, worker_id)
VALUES ($1, $2, $3, $4)
RETURNING id, context_id, role, content, timestamp, worker_id
`

type CreateMessageParams struct {
	ContextID pgtype.UUID
	Role      string
	Content   string
	WorkerID  pgtype.UUID
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ContextID,
		arg.Role,
		arg.Content,
		arg.WorkerID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.Role,
		&i.Content,
		&i.Timestamp,
		&i.WorkerID,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, context_id, role, content, timestamp, worker_id FROM messages
WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id int32) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.Role,
		&i.Content,
		&i.Timestamp,
		&i.WorkerID,
	)
	return i, err
}

const listMessagesByContext = `-- name: ListMessagesByContext :many
SELECT id, context_id, role, content, timestamp, worker_id FROM messages
WHERE context_id = $1
ORDER BY timestamp ASC
`

func (q *Queries) ListMessagesByContext(ctx context.Context, contextID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByContext, contextID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ContextID,
			&i.Role,
			&i.Content,
			&i.Timestamp,
			&i.WorkerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByConversation = `-- name: ListMessagesByConversation :many
SELECT m.id, m.context_id, m.role, m.content, m.timestamp, m.worker_id FROM messages m
JOIN contexts c ON m.context_id = c.id
WHERE c.id = (
    SELECT id FROM contexts
    WHERE contexts.conversation_id = $1
    ORDER BY timestamp DESC
    LIMIT 1
)
ORDER BY m.timestamp ASC
`

func (q *Queries) ListMessagesByConversation(ctx context.Context, conversationID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ContextID,
			&i.Role,
			&i.Content,
			&i.Timestamp,
			&i.WorkerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
