// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ConversationState string

const (
	ConversationStateIdle       ConversationState = "idle"
	ConversationStateProcessing ConversationState = "processing"
	ConversationStateCompleted  ConversationState = "completed"
	ConversationStateErrored    ConversationState = "errored"
)

func (e *ConversationState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConversationState(s)
	case string:
		*e = ConversationState(s)
	default:
		return fmt.Errorf("unsupported scan type for ConversationState: %T", src)
	}
	return nil
}

type NullConversationState struct {
	ConversationState ConversationState
	Valid             bool // Valid is true if ConversationState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConversationState) Scan(value interface{}) error {
	if value == nil {
		ns.ConversationState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConversationState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConversationState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConversationState), nil
}

type ConversationType string

const (
	ConversationTypeTask         ConversationType = "task"
	ConversationTypeConversation ConversationType = "conversation"
)

func (e *ConversationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConversationType(s)
	case string:
		*e = ConversationType(s)
	default:
		return fmt.Errorf("unsupported scan type for ConversationType: %T", src)
	}
	return nil
}

type NullConversationType struct {
	ConversationType ConversationType
	Valid            bool // Valid is true if ConversationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConversationType) Scan(value interface{}) error {
	if value == nil {
		ns.ConversationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConversationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConversationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConversationType), nil
}

type JobState string

const (
	JobStatePending    JobState = "pending"
	JobStateProcessing JobState = "processing"
	JobStateWaiting    JobState = "waiting"
	JobStateProcessed  JobState = "processed"
	JobStateErrored    JobState = "errored"
)

func (e *JobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobState(s)
	case string:
		*e = JobState(s)
	default:
		return fmt.Errorf("unsupported scan type for JobState: %T", src)
	}
	return nil
}

type NullJobState struct {
	JobState JobState
	Valid    bool // Valid is true if JobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobState) Scan(value interface{}) error {
	if value == nil {
		ns.JobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobState), nil
}

type Context struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Timestamp      pgtype.Timestamptz
}

type Conversation struct {
	ID        pgtype.UUID
	State     ConversationState
	Type      ConversationType
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type JobQueue struct {
	ID          pgtype.UUID
	Content     string
	Timestamp   pgtype.Timestamptz
	WorkerID    pgtype.UUID
	State       JobState
	LockedUntil pgtype.Timestamptz
	Payload     []byte
}

type Message struct {
	ID        int32
	ContextID pgtype.UUID
	Role      string
	Content   string
	Timestamp pgtype.Timestamptz
	WorkerID  pgtype.UUID
}

type Worker struct {
	ID pgtype.UUID
}
